[[redirects]]
  from = "/api/*"
  to = "https://bluesky-backend-production.up.railway.app/api/:splat"
  status = 200
  force = true

# SPA fallback - serve index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200